import Head from 'next/head';
import { string } from 'prop-types';

export default function Slug({ slug }) {
	return (
		<div>
			<Head>
				<title>{slug}</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>This is slug: {slug}</main>
		</div>
	);
}

export const getServerSideProps = async ({ query }) => {
	try {
		return {
			props: {
				slug: query.slug,
			},
		};
	} catch (err) {
		return {
			notFound: true,
		};
	}
};

Slug.propTypes = {
	slug: string,
};
